import { readFileSync } from "node:fs";
import path from "node:path";
import type { NextConfig } from "next";

/**
 * Revenue beneficiaries recorded by the last deployment.
 *
 * `config/contracts.json` is generated by `contracts/scripts/deploy-testnet.ts` and is not tracked,
 * so it is read here - in Node, at config load - rather than imported from `src/lib/chain.ts`.
 * A JSON import there would make the client bundle depend on a file a fresh checkout does not
 * have, turning a missing manifest into a build failure; reading it here degrades to no fallback
 * and the variables below win anyway whenever they are set.
 */
function deploymentBeneficiaries(): { operator?: string; developer?: string; btcRevenueAddress?: string } {
  try {
    const manifest = JSON.parse(readFileSync(path.join(__dirname, "config", "contracts.json"), "utf8")) as {
      beneficiaries?: { operator?: string; developer?: string; btcRevenueAddress?: string };
    };
    return manifest.beneficiaries ?? {};
  } catch {
    return {};
  }
}

const beneficiaries = deploymentBeneficiaries();

const nextConfig: NextConfig = {
  reactStrictMode: true,
  // The SDK is consumed straight from the sibling workspace package. Its `frontend/node_modules`
  // entry is a junction to `../sdk`, which sits outside this project directory, so Turbopack needs
  // the workspace root - the same directory webpack walks up to on its own.
  transpilePackages: ["@maotang/sdk"],
  turbopack: {
    root: path.resolve(__dirname, ".."),
  },
  // Forwarded from the deployment manifest so the board can name its revenue beneficiaries even
  // when the NEXT_PUBLIC_OPERATOR_ADDRESS / _DEVELOPER_ADDRESS / _BTC_REVENUE_ADDRESS trio is unset.
  env: {
    NEXT_PUBLIC_MANIFEST_OPERATOR_ADDRESS: beneficiaries.operator ?? "",
    NEXT_PUBLIC_MANIFEST_DEVELOPER_ADDRESS: beneficiaries.developer ?? "",
    NEXT_PUBLIC_MANIFEST_BTC_REVENUE_ADDRESS: beneficiaries.btcRevenueAddress ?? "",
  },
};

export default nextConfig;
