"""
Data Models for the Financial Clearing Engine
==============================================

Defines the core data structures for the Success-Share Factory:
  - TaskValuation: How much value a task generates
  - ProfitSplit: How profits are divided
  - ServiceFee: The fee structure
  - SuccessMetrics: Key performance indicators
  - GrowthRecord: Historical growth tracking
"""

from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Optional
from enum import Enum


class ServiceTier(Enum):
    """Service tiers with different fee structures."""
    CORE = "core"           # Basic task execution — 10%
    PREMIUM = "premium"     # Multi-agent orchestration — 20%
    ENTERPRISE = "enterprise"  # Full factory pipeline — 30%


class TaskCategory(Enum):
    """Categories of tasks for valuation purposes."""
    CONTENT_PRODUCTION = "content_production"
    SOFTWARE_DEV = "software_development"
    MARKET_RESEARCH = "market_research"
    FINANCIAL_ANALYSIS = "financial_analysis"
    DEPLOYMENT = "deployment"
    DATA_PIPELINE = "data_pipeline"
    STRATEGY = "strategy"
    OTHER = "other"


@dataclass
class ServiceFee:
    """
    Service fee configuration for a task or contract.
    
    The fee is calculated as a percentage of net profit generated.
    """
    tier: ServiceTier = ServiceTier.CORE
    percentage: float = 0.10  # 10% default for CORE tier
    minimum_fee: float = 0.0  # Minimum fee in USD
    maximum_fee: Optional[float] = None  # Cap in USD (None = no cap)
    
    @classmethod
    def from_tier(cls, tier: ServiceTier) -> "ServiceFee":
        """Create a ServiceFee from a tier with standard rates."""
        rates = {
            ServiceTier.CORE: 0.10,
            ServiceTier.PREMIUM: 0.20,
            ServiceTier.ENTERPRISE: 0.30,
        }
        return cls(tier=tier, percentage=rates[tier])
    
    def calculate_fee(self, net_profit: float) -> float:
        """Calculate the service fee based on net profit."""
        fee = net_profit * self.percentage
        if fee < self.minimum_fee:
            fee = self.minimum_fee
        if self.maximum_fee is not None and fee > self.maximum_fee:
            fee = self.maximum_fee
        return round(fee, 2)


@dataclass
class TaskValuation:
    """
    Valuation of a completed task.
    
    Measures the business value generated by a task execution.
    """
    task_id: str
    category: TaskCategory
    estimated_value: float  # Estimated business value in USD
    actual_value: float = 0.0  # Actual measured value (updated post-execution)
    cost_incurred: float = 0.0  # API costs, compute, etc.
    time_saved_hours: float = 0.0  # Estimated human hours saved
    quality_score: float = 1.0  # 0.0 to 1.0 — execution quality
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    
    @property
    def net_profit(self) -> float:
        """Net profit = actual_value - cost_incurred."""
        return max(0.0, self.actual_value - self.cost_incurred)
    
    @property
    def roi(self) -> float:
        """Return on Investment as a multiplier."""
        if self.cost_incurred <= 0:
            return float('inf') if self.actual_value > 0 else 0.0
        return round(self.actual_value / self.cost_incurred, 2)
    
    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class ProfitSplit:
    """
    A profit split record for a single task.
    
    Documents how the value generated by a task is divided between
    the client and the Maneki-AI factory.
    """
    task_id: str
    valuation: TaskValuation
    service_fee: ServiceFee
    gross_value: float  # Total value generated
    net_profit: float  # Gross value minus costs
    service_charge: float  # Fee deducted
    client_share: float  # What the client keeps
    factory_share: float  # What the factory earns
    settled: bool = False  # Whether this split has been settled
    settled_at: Optional[str] = None
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    
    @classmethod
    def calculate(cls, task_id: str, valuation: TaskValuation, 
                  fee: ServiceFee) -> "ProfitSplit":
        """Calculate a profit split from a valuation and fee structure."""
        net_profit = valuation.net_profit
        service_charge = fee.calculate_fee(net_profit)
        client_share = net_profit - service_charge
        
        return cls(
            task_id=task_id,
            valuation=valuation,
            service_fee=fee,
            gross_value=valuation.actual_value,
            net_profit=net_profit,
            service_charge=service_charge,
            client_share=client_share,
            factory_share=service_charge,
        )
    
    def settle(self) -> None:
        """Mark this profit split as settled."""
        self.settled = True
        self.settled_at = datetime.now(timezone.utc).isoformat()
    
    def to_dict(self) -> dict:
        result = asdict(self)
        result["valuation"] = self.valuation.to_dict()
        result["service_fee"] = asdict(self.service_fee)
        return result


@dataclass
class SuccessMetrics:
    """
    Aggregate success metrics for the factory.
    
    Tracks overall performance indicators that demonstrate
    the value of the Success-Share model.
    """
    total_tasks_completed: int = 0
    total_value_generated: float = 0.0
    total_costs_incurred: float = 0.0
    total_service_fees: float = 0.0
    total_client_savings: float = 0.0  # Time/money saved for clients
    average_roi: float = 0.0
    success_rate: float = 1.0  # Percentage of tasks that met success criteria
    period_start: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    period_end: Optional[str] = None
    
    @property
    def total_net_profit(self) -> float:
        return max(0.0, self.total_value_generated - self.total_costs_incurred)
    
    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class GrowthRecord:
    """
    A record of growth over a time period.
    
    Used to track the "Shared Growth" aspect of the business model —
    demonstrating how the factory's efficiency improves over time.
    """
    period: str  # e.g., "2026-06", "2026-Q2"
    tasks_completed: int
    total_value: float
    total_costs: float
    total_fees: float
    avg_roi: float
    efficiency_gain: float  # Percentage improvement vs previous period
    notes: str = ""
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    
    def to_dict(self) -> dict:
        return asdict(self)
