import os
import subprocess


BACKEND_MAIN_PY = '''# -*- coding: utf-8 -*-
# White Dragon Horse · CEO Console Backend
# Generated by TRAE (TraeAuto.generate_backend)
import asyncio
import functools
import json
import os
import sys
import threading

# ensure the white_dragon_horse project root is importable
_BACKEND_DIR = os.path.dirname(os.path.abspath(__file__))
_CONSOLE_DIR = os.path.dirname(_BACKEND_DIR)
_PROJECT_ROOT = os.path.dirname(_CONSOLE_DIR)
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
import uvicorn

from {ORCH_MODULE} import {ORCH_CLASS}

app = FastAPI(title="White Dragon Horse · CEO Console", version="0.1.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

orchestrator = {ORCH_CLASS}()

# ---------- log hub (thread-safe, broadcasts to /ws/logs clients) ----------
class LogHub:
    def __init__(self):
        self.clients = set()
        self.lock = threading.Lock()

    def connect(self, ws):
        with self.lock:
            self.clients.add(ws)

    def disconnect(self, ws):
        with self.lock:
            self.clients.discard(ws)


hub = LogHub()
MAIN_LOOP = None


@app.on_event("startup")
async def _capture_loop():
    global MAIN_LOOP
    MAIN_LOOP = asyncio.get_running_loop()


def broadcast(type_, **data):
    """Thread-safe broadcast to every connected WebSocket client."""
    if MAIN_LOOP is None:
        return
    msg = json.dumps({"type": type_, **data}, ensure_ascii=False)
    for ws in list(hub.clients):
        try:
            asyncio.run_coroutine_threadsafe(ws.send_text(msg), MAIN_LOOP)
        except Exception:
            hub.disconnect(ws)


# ---------- static frontend (ZOO generated) ----------
@app.get("/")
@app.get("/ceo-dashboard")
async def dashboard():
    return FileResponse(os.path.join(_CONSOLE_DIR, "index.html"))


@app.get("/style.css")
async def style_css():
    return FileResponse(os.path.join(_CONSOLE_DIR, "style.css"))


@app.get("/app.js")
async def app_js():
    return FileResponse(os.path.join(_CONSOLE_DIR, "app.js"))


# ---------- pipeline handlers (wired into White Dragon Horse) ----------
def run_full_pipeline():
    broadcast("pipeline", step=0)
    broadcast("log", text="AGI receive task")
    task = orchestrator.agi.receive()
    broadcast("pipeline", step=1)
    broadcast("log", text="ZOO generate code")
    orchestrator.zoo.generate("auto", {"task": task})
    broadcast("pipeline", step=2)
    broadcast("log", text="TRAE execute")
    orchestrator.trae.run("scripts/start_agent_v2.py")
    broadcast("pipeline", step=3)
    broadcast("log", text="Huginn monitor")
    orchestrator.huginn.monitor_file("logs")
    result = orchestrator.n8n.execute({"task": "full_pipeline"})
    return {"pipeline": "complete", "result": result}


def run_zoo_generation():
    broadcast("log", text="ZOO generating frontend/code")
    return orchestrator.zoo.generate("auto", {"task": "zoo_generation"})


def run_trae_execution():
    broadcast("log", text="TRAE executing scripts/start_agent_v2.py")
    orchestrator.trae.run("scripts/start_agent_v2.py")
    return {"executed": "scripts/start_agent_v2.py"}


def run_tagui_browser():
    broadcast("log", text="TagUI running agent/tagui/zoo_login.tag")
    ok = orchestrator.tagui.run_flow("agent/tagui/zoo_login.tag")
    return {"status": bool(ok), "flow": "agent/tagui/zoo_login.tag"}


def run_daily_tasks():
    broadcast("log", text="n8n running daily tasks")
    return orchestrator.n8n.execute({"task": "daily_summary"})


def run_generic(action):
    broadcast("log", text=f"no dedicated handler for '{action}'; running orchestrator")
    return orchestrator.n8n.execute({"task": action})


RUN_HANDLERS = {RUN_HANDLERS_DICT}


def _invoke(handler, action):
    if handler is run_generic:
        return handler(action)
    return handler()


@app.post("/api/run/{action}")
async def run_action(action: str):
    handler = globals().get(RUN_HANDLERS.get(action, "run_generic"), run_generic)
    broadcast("status", key=action, state="run")
    try:
        loop = asyncio.get_running_loop()
        result = await loop.run_in_executor(None, functools.partial(_invoke, handler, action))
        broadcast("status", key=action, state="ok")
        return {"ok": True, "action": action, "result": result}
    except Exception as e:
        broadcast("status", key=action, state="error")
        broadcast("log", text=f"{action} failed: {e}", cls="err")
        return JSONResponse({"ok": False, "action": action, "message": str(e)}, status_code=500)


# ---------- WebSocket log stream ----------
@app.websocket("{WS_PATH}")
async def ws_logs(ws: WebSocket):
    await ws.accept()
    hub.connect(ws)
    await ws.send_text(json.dumps({"type": "log", "text": "connected: White Dragon Horse log stream"}, ensure_ascii=False))
    broadcast("status", key="pipeline", state="idle")
    try:
        while True:
            await ws.receive_text()
    except WebSocketDisconnect:
        hub.disconnect(ws)


if __name__ == "__main__":
    print("✅ White Dragon Horse · CEO Console -> http://0.0.0.0:8080/ceo-dashboard (PC & phone)")
    uvicorn.run(app, host="0.0.0.0", port=8080)
'''


class TraeAuto:
    def run(self, script, timeout=8):
        print(f'[TRAE] Running script: {script}')
        try:
            subprocess.run(['python', script], timeout=timeout)
        except subprocess.TimeoutExpired:
            print(f'[TRAE] WARNING: script timed out after {timeout}s; continuing')
        except FileNotFoundError as e:
            print(f'[TRAE] WARNING: cannot run script ({e}); continuing')

    def build(self, project):
        print(f'[TRAE] Building project: {project}')

    def test(self, project):
        print(f'[TRAE] Testing project: {project}')

    def generate_backend(self, project_root='ceo_console', api=None, orchestrator_import='agent.dragon_core_v2.WhiteDragonHorseV2'):
        """Generate a FastAPI backend (control API + WebSocket) wired into White Dragon Horse."""
        api = api or {}
        endpoints = api.get('endpoints', [])
        ws_path = (api.get('websocket') or {}).get('path', '/ws/logs')

        run_handlers = {}
        for ep in endpoints:
            seg = ep.get('path', '').rstrip('/').split('/')[-1]
            if seg:
                run_handlers[seg] = ep.get('action', 'run_generic')

        root = os.path.join(os.getcwd(), project_root)
        backend_dir = os.path.join(root, 'backend')
        os.makedirs(backend_dir, exist_ok=True)

        orch_module, orch_class = orchestrator_import.rsplit('.', 1)
        content = (
            BACKEND_MAIN_PY
            .replace('{ORCH_MODULE}', orch_module)
            .replace('{ORCH_CLASS}', orch_class)
            .replace('{RUN_HANDLERS_DICT}', repr(run_handlers))
            .replace('{WS_PATH}', ws_path)
        )

        main_path = os.path.join(backend_dir, 'main.py')
        with open(main_path, 'w', encoding='utf-8') as f:
            f.write(content)

        # allow `python -m uvicorn ceo_console.backend.main:app` as well
        init_path = os.path.join(backend_dir, '__init__.py')
        if not os.path.exists(init_path):
            with open(init_path, 'w', encoding='utf-8') as f:
                f.write('')

        print(f'[TRAE] Backend generated at {main_path}')
        return {
            'result': 'generated',
            'path': main_path,
            'framework': api.get('framework', 'fastapi'),
            'endpoints': endpoints,
            'websocket': ws_path,
            'orchestrator': orchestrator_import,
        }
