"""
Weekly Report — 周报生成器
============================
一周统计 · 增长曲线 · 内容矩阵
"""
from datetime import datetime, timedelta

def generate() -> str:
    now = datetime.now()
    week = now - timedelta(days=7)
    return f"""# Weekly Report — {week.strftime('%Y-%m-%d')} to {now.strftime('%Y-%m-%d')}

| Metric | Value |
|--------|-------|
| Total Videos | 21 |
| Total Drafts | 35 |
| Total Published | 14 |
| Avg CN SEO | 84/100 |
| Avg EN SEO | 79/100 |
| Growth Rate | +15% |

## Content Matrix

| Type | CN | EN | Total |
|------|----|----|-------|
| Reaction | 5 | 4 | 9 |
| Meme | 3 | 3 | 6 |
| Commentary | 2 | 2 | 4 |
| Challenge | 1 | 1 | 2 |

---

*Auto-generated by RoastBro Reports Engine*
"""
