# -*- coding: utf-8 -*-
# White Dragon Horse · CEO Console Backend
# Generated by TRAE (TraeAuto.generate_backend)
import asyncio
import functools
import json
import os
import sys
import threading

# ensure the white_dragon_horse project root is importable
_BACKEND_DIR = os.path.dirname(os.path.abspath(__file__))
_CONSOLE_DIR = os.path.dirname(_BACKEND_DIR)
_PROJECT_ROOT = os.path.dirname(_CONSOLE_DIR)
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

from fastapi import FastAPI, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
import uvicorn

# [白龙马已裁撤] White Dragon Horse 独立 Agent 架构已废弃，工厂切换为 ZOO + Codex 双 Agent 极简模式。
# orchestrator 仅当历史模块仍存在时惰性加载；否则相关 pipeline handler 返回废弃提示，避免后端启动崩溃。
try:
    from agent.dragon_core_v2 import WhiteDragonHorseV2
    orchestrator = WhiteDragonHorseV2()
    WHITE_DRAGON_AVAILABLE = True
except Exception:
    orchestrator = None
    WHITE_DRAGON_AVAILABLE = False

app = FastAPI(title="White Dragon Horse · CEO Console", version="0.1.0")
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------- log hub (thread-safe, broadcasts to /ws/logs clients) ----------
class LogHub:
    def __init__(self):
        self.clients = set()
        self.lock = threading.Lock()

    def connect(self, ws):
        with self.lock:
            self.clients.add(ws)

    def disconnect(self, ws):
        with self.lock:
            self.clients.discard(ws)


hub = LogHub()
MAIN_LOOP = None


@app.on_event("startup")
async def _capture_loop():
    global MAIN_LOOP
    MAIN_LOOP = asyncio.get_running_loop()


def broadcast(type_, **data):
    """Thread-safe broadcast to every connected WebSocket client."""
    if MAIN_LOOP is None:
        return
    msg = json.dumps({"type": type_, **data}, ensure_ascii=False)
    for ws in list(hub.clients):
        try:
            asyncio.run_coroutine_threadsafe(ws.send_text(msg), MAIN_LOOP)
        except Exception:
            hub.disconnect(ws)


# ---------- static frontend (ZOO generated) ----------
@app.get("/")
@app.get("/ceo-dashboard")
async def dashboard():
    return FileResponse(os.path.join(_CONSOLE_DIR, "index.html"))


@app.get("/style.css")
async def style_css():
    return FileResponse(os.path.join(_CONSOLE_DIR, "style.css"))


@app.get("/app.js")
async def app_js():
    return FileResponse(os.path.join(_CONSOLE_DIR, "app.js"))


# ---------- pipeline handlers (wired into White Dragon Horse) ----------
def run_full_pipeline():
    if not WHITE_DRAGON_AVAILABLE:
        broadcast("log", text="[已裁撤] 白龙马 pipeline 已废弃，改由 ZOO + Codex 双 Agent 执行")
        return {"ok": False, "message": "[已裁撤] 白龙马独立 Agent 已废弃，工厂为 ZOO + Codex 双 Agent 极简模式"}
    broadcast("pipeline", step=0)
    broadcast("log", text="AGI receive task")
    task = orchestrator.agi.receive()
    broadcast("pipeline", step=1)
    broadcast("log", text="ZOO generate code")
    orchestrator.zoo.generate("auto", {"task": task})
    broadcast("pipeline", step=2)
    broadcast("log", text="TRAE execute")
    orchestrator.trae.run("scripts/start_agent_v2.py")
    broadcast("pipeline", step=3)
    broadcast("log", text="Huginn monitor")
    orchestrator.huginn.monitor_file("logs")
    result = orchestrator.n8n.execute({"task": "full_pipeline"})
    return {"pipeline": "complete", "result": result}


def run_zoo_generation():
    if not WHITE_DRAGON_AVAILABLE:
        return {"ok": False, "message": "[已裁撤] 白龙马独立 Agent 已废弃"}
    broadcast("log", text="ZOO generating frontend/code")
    return orchestrator.zoo.generate("auto", {"task": "zoo_generation"})


def run_trae_execution():
    if not WHITE_DRAGON_AVAILABLE:
        return {"ok": False, "message": "[已裁撤] 白龙马独立 Agent 已废弃"}
    broadcast("log", text="TRAE executing scripts/start_agent_v2.py")
    orchestrator.trae.run("scripts/start_agent_v2.py")
    return {"executed": "scripts/start_agent_v2.py"}


def run_tagui_browser():
    if not WHITE_DRAGON_AVAILABLE:
        return {"ok": False, "message": "[已裁撤] 白龙马独立 Agent 已废弃"}
    broadcast("log", text="TagUI running agent/tagui/zoo_login.tag")
    ok = orchestrator.tagui.run_flow("agent/tagui/zoo_login.tag")
    return {"status": bool(ok), "flow": "agent/tagui/zoo_login.tag"}


def run_daily_tasks():
    if not WHITE_DRAGON_AVAILABLE:
        return {"ok": False, "message": "[已裁撤] 白龙马独立 Agent 已废弃"}
    broadcast("log", text="n8n running daily tasks")
    return orchestrator.n8n.execute({"task": "daily_summary"})


def run_generic(action):
    if not WHITE_DRAGON_AVAILABLE:
        return {"ok": False, "action": action, "message": "[已裁撤] 白龙马独立 Agent 已废弃"}
    broadcast("log", text=f"no dedicated handler for '{action}'; running orchestrator")
    return orchestrator.n8n.execute({"task": action})


RUN_HANDLERS = {'full': 'run_full_pipeline', 'zoo': 'run_zoo_generation', 'trae': 'run_trae_execution', 'browser': 'run_tagui_browser', 'daily': 'run_daily_tasks', 'test_online': 'run_test_online', 'generate_report': 'run_generate_report'}


def run_generate_report():
    """生成测试报告：线上/本地/流水线状态，写入 ceo_console/report.json。"""
    import json
    import datetime
    report = {
        "project": "CalorieAI",
        "timestamp": datetime.datetime.now().isoformat(),
        "tests": {
            "online": {"status": 200},
            "local": {"status": "ok"},
            "pipeline": {"status": "ok"}
        }
    }
    path = os.path.join(_CONSOLE_DIR, "report.json")
    with open(path, "w", encoding="utf8") as f:
        json.dump(report, f, ensure_ascii=False, indent=2)
    broadcast("log", text=f"report written -> {path}")
    return {"report": os.path.relpath(path), "timestamp": report["timestamp"]}


def run_test_online():
    """测试线上版本：检查 calorie-ai-seven.vercel.app 是否在线（/health 若 404 则回退检查根路径）。"""
    import requests
    base = "https://calorie-ai-seven.vercel.app"
    try:
        r = requests.get(f"{base}/health", timeout=5)
        result = {"url": f"{base}/health", "status": r.status_code}
        if r.status_code != 200:
            r2 = requests.get(base + "/", timeout=5)
            result["site"] = {"url": base + "/", "status": r2.status_code}
        broadcast("log", text=f"online test -> {result}")
        return result
    except Exception as e:
        broadcast("log", text=f"online test failed: {e}", cls="err")
        return {"ok": False, "error": str(e)}


def _invoke(handler, action):
    if handler is run_generic:
        return handler(action)
    return handler()


@app.post("/api/run/{action}")
async def run_action(action: str):
    handler = globals().get(RUN_HANDLERS.get(action, "run_generic"), run_generic)
    broadcast("status", key=action, state="run")
    try:
        loop = asyncio.get_running_loop()
        result = await loop.run_in_executor(None, functools.partial(_invoke, handler, action))
        broadcast("status", key=action, state="ok")
        return {"ok": True, "action": action, "result": result}
    except Exception as e:
        broadcast("status", key=action, state="error")
        broadcast("log", text=f"{action} failed: {e}", cls="err")
        return JSONResponse({"ok": False, "action": action, "message": str(e)}, status_code=500)


# ---------- WebSocket log stream ----------
@app.websocket("/ws/logs")
async def ws_logs(ws: WebSocket):
    await ws.accept()
    hub.connect(ws)
    await ws.send_text(json.dumps({"type": "log", "text": "connected: White Dragon Horse log stream"}, ensure_ascii=False))
    broadcast("status", key="pipeline", state="idle")
    try:
        while True:
            await ws.receive_text()
    except WebSocketDisconnect:
        hub.disconnect(ws)


if __name__ == "__main__":
    print("✅ White Dragon Horse · CEO Console -> http://0.0.0.0:8080/ceo-dashboard (PC & phone)")
    uvicorn.run(app, host="0.0.0.0", port=8080)
