// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {IZKVerifier} from "./interfaces/IZKVerifier.sol";

/// @title Groth16Verifier
/// @notice Groth16 verifier over BN254 (alt_bn128) for the protocol's nullifier proofs.
/// @dev Implements the standard Groth16 verification equation
///
///      `e(-A, B) * e(alpha, beta) * e(vk_x, gamma) * e(C, delta) == 1`
///
///      using the EIP-197 pairing precompile (0x08) together with EIP-196 point addition and
///      multiplication (0x06, 0x07). Artifacts are consumed exactly as SnarkJS/Circom emit them:
///
///      * proof limbs are `[a.x, a.y, b.x.c0, b.x.c1, b.y.c0, b.y.c1, c.x, c.y]`, the SnarkJS
///        `pi_a` / `pi_b` / `pi_c` JSON order, where an element `a*i + b` of F_p^2 is written
///        `[c0, c1] = [b, a]`;
///      * `vk_x = ic[0] + sum(publicInputs[i] * ic[i + 1])`;
///      * the public input list is fixed to exactly one element, the nullifier hash, so a key with
///        any other arity is rejected at configuration time instead of silently verifying nothing.
///
///      Coordinates are range-checked here; curve and subgroup validity are enforced by the pairing
///      and group precompiles themselves, which reject invalid inputs, so the checks are equivalent
///      to the ones in a verifier generated by `snarkjs zkey export solidityverifier` - minus the
///      re-implementation of F_p^2 subgroup tests that the precompiles already perform.
///
///      The verification key is deliberately *not* hardcoded. No audited circuit or ceremony result
///      exists in this repository yet, so the owner installs the key produced by the trusted setup of
///      record and then calls {lockVerificationKey} to remove the ability to swap the key after
///      launch (a swapped key can forge personhood for arbitrary nullifiers). Until a key is
///      installed, and after locking, verification fails closed.
contract Groth16Verifier is IZKVerifier {
    /// @notice BN254 base field modulus (Fq); every coordinate must be strictly below it.
    uint256 public constant FIELD_MODULUS =
        21888242871839275222246405745257275088696311157297823662689037894645226208583;

    /// @notice BN254 scalar field modulus (Fr); every scalar must be strictly below it.
    /// @dev Rejecting non-canonical scalars also prevents nullifier aliasing: two byte strings that
    /// differ only by a multiple of the group order must not both be usable as public inputs.
    uint256 public constant SCALAR_FIELD =
        21888242871839275222246405745257275088548364400416034343698204186575808495617;

    /// @notice Number of 32-byte limbs in an ABI-encoded proof.
    uint256 public constant PROOF_LIMBS = 8;

    /// @notice Number of public inputs this verifier accepts: the nullifier hash.
    uint256 public constant PUBLIC_INPUT_COUNT = 1;

    /// @notice Gas budget forwarded to the EIP-197 pairing precompile.
    /// @dev The precompile consumes *every* unit of gas forwarded to it when it rejects its input
    /// (off-curve point, malformed F_p^2 element). Forwarding `gas()` would therefore let a single
    /// malformed proof drain the caller's frame instead of failing closed. Four pairs cost at most
    /// 420_000 gas under the Byzantium schedule (181_000 under Istanbul), so this budget is
    /// comfortable; on a chain that priced pairing higher, verification would fail closed rather
    /// than accept an unproven statement.
    uint256 public constant PAIRING_GAS_BUDGET = 1_000_000;

    /// @notice A Groth16 verification key, encoded as SnarkJS exports it.
    /// @dev G1 points are `[x, y]`. Elements of F_p^2 are `[c0, c1]`, the real and imaginary parts of
    /// `c0 + c1 * i`; note that this differs from the EIP-197 wire order used internally, which puts
    /// the imaginary part first. `ic` holds `PUBLIC_INPUT_COUNT + 1` G1 points.
    struct VerificationKey {
        uint256[2] alpha1;
        uint256[4] beta2;
        uint256[4] gamma2;
        uint256[4] delta2;
        uint256[2][] ic;
    }

    /// @notice Deployment authority allowed to install the verification key.
    address public immutable owner;

    /// @notice Digest of the installed key, so an off-chain audit can pin it to the ceremony output.
    bytes32 public verificationKeyHash;

    /// @notice True once the key is frozen and can no longer be replaced.
    bool public verificationKeyLocked;

    VerificationKey private _verificationKey;

    event VerificationKeyInstalled(bytes32 indexed verificationKeyHash, uint256 icLength);
    event VerificationKeyLocked(bytes32 indexed verificationKeyHash);

    error InvalidOwner();
    error NotOwner(address caller);
    error VerificationKeyAlreadyLocked();
    error InvalidVerificationKey();
    error GroupOperationFailed();

    /// @param owner_ Address allowed to install the key; use a multisig or timelock in production.
    constructor(address owner_) {
        if (owner_ == address(0)) revert InvalidOwner();
        owner = owner_;
    }

    modifier onlyOwner() {
        if (msg.sender != owner) revert NotOwner(msg.sender);
        _;
    }

    /// @notice True when a usable verification key is installed.
    function isConfigured() external view returns (bool) {
        return _verificationKey.ic.length == PUBLIC_INPUT_COUNT + 1;
    }

    /// @notice Installs the verification key produced by the trusted setup of record.
    /// @dev Reverts for a wrong-arity or out-of-range key. A key whose points are off-curve is
    /// rejected later by the precompiles, which makes verification fail closed rather than succeed.
    function setVerificationKey(VerificationKey calldata verificationKey) external onlyOwner {
        if (verificationKeyLocked) revert VerificationKeyAlreadyLocked();
        if (!_isValidVerificationKey(verificationKey)) revert InvalidVerificationKey();

        delete _verificationKey;
        VerificationKey storage stored = _verificationKey;

        stored.alpha1[0] = verificationKey.alpha1[0];
        stored.alpha1[1] = verificationKey.alpha1[1];
        for (uint256 i = 0; i < 4; ++i) {
            stored.beta2[i] = verificationKey.beta2[i];
            stored.gamma2[i] = verificationKey.gamma2[i];
            stored.delta2[i] = verificationKey.delta2[i];
        }
        for (uint256 i = 0; i < verificationKey.ic.length; ++i) {
            stored.ic.push([verificationKey.ic[i][0], verificationKey.ic[i][1]]);
        }

        bytes32 digest = keccak256(
            abi.encode(
                verificationKey.alpha1,
                verificationKey.beta2,
                verificationKey.gamma2,
                verificationKey.delta2,
                verificationKey.ic
            )
        );
        verificationKeyHash = digest;

        emit VerificationKeyInstalled(digest, verificationKey.ic.length);
    }

    /// @notice Freezes the installed key permanently. Irreversible by design.
    function lockVerificationKey() external onlyOwner {
        if (verificationKeyHash == bytes32(0)) revert InvalidVerificationKey();
        if (verificationKeyLocked) revert VerificationKeyAlreadyLocked();
        verificationKeyLocked = true;
        emit VerificationKeyLocked(verificationKeyHash);
    }

    /// @notice Verifies a personhood or hardware proof against the installed key.
    /// @param proof `abi.encode(uint256[8])` in SnarkJS limb order; any other length returns false.
    /// @param nullifierHash The single public input.
    function verifyProof(bytes calldata proof, bytes32 nullifierHash) external view returns (bool) {
        if (proof.length != PROOF_LIMBS * 32) return false;
        uint256[8] memory limbs = abi.decode(proof, (uint256[8]));
        return _verify(limbs, uint256(nullifierHash));
    }

    function _verify(uint256[8] memory proof, uint256 publicInput) private view returns (bool) {
        VerificationKey storage vk = _verificationKey;

        // Fail closed while unconfigured, or if a key of the wrong arity ever got stored.
        if (vk.ic.length != PUBLIC_INPUT_COUNT + 1) return false;
        if (publicInput >= SCALAR_FIELD) return false;

        for (uint256 i = 0; i < PROOF_LIMBS; ++i) {
            if (proof[i] >= FIELD_MODULUS) return false;
        }

        // vk_x = ic[0] + publicInput * ic[1]
        uint256[2] memory scaled = _ecMul(vk.ic[1], publicInput);
        uint256[2] memory vkX = _ecAdd(vk.ic[0], scaled);

        return _pairingCheck(proof, vkX, vk);
    }

    /// @dev Builds the 4-pair EIP-197 input and requires the pairing product to be exactly one.
    /// The G2 coordinates are emitted imaginary-first, which is the wire order EIP-197 mandates and
    /// the opposite of the SnarkJS JSON order held in storage.
    function _pairingCheck(uint256[8] memory proof, uint256[2] memory vkX, VerificationKey storage vk)
        private
        view
        returns (bool)
    {
        uint256[24] memory input;

        // e(-A, B)
        input[0] = proof[0];
        input[1] = proof[1] == 0 ? 0 : FIELD_MODULUS - proof[1];
        input[2] = proof[3];
        input[3] = proof[2];
        input[4] = proof[5];
        input[5] = proof[4];

        // e(alpha, beta)
        input[6] = vk.alpha1[0];
        input[7] = vk.alpha1[1];
        input[8] = vk.beta2[1];
        input[9] = vk.beta2[0];
        input[10] = vk.beta2[3];
        input[11] = vk.beta2[2];

        // e(vk_x, gamma)
        input[12] = vkX[0];
        input[13] = vkX[1];
        input[14] = vk.gamma2[1];
        input[15] = vk.gamma2[0];
        input[16] = vk.gamma2[3];
        input[17] = vk.gamma2[2];

        // e(C, delta)
        input[18] = proof[6];
        input[19] = proof[7];
        input[20] = vk.delta2[1];
        input[21] = vk.delta2[0];
        input[22] = vk.delta2[3];
        input[23] = vk.delta2[2];

        uint256[1] memory product;
        bool ok;
        uint256 budget = PAIRING_GAS_BUDGET;
        assembly {
            ok := staticcall(budget, 0x08, input, 0x300, product, 0x20)
        }
        return ok && product[0] == 1;
    }

    /// @dev EIP-196 point addition. Reverts only for keys the configuration step should have caught.
    function _ecAdd(uint256[2] memory a, uint256[2] memory b) private view returns (uint256[2] memory out) {
        uint256[4] memory input = [a[0], a[1], b[0], b[1]];
        bool ok;
        assembly {
            ok := staticcall(gas(), 0x06, input, 0x80, out, 0x40)
        }
        if (!ok) revert GroupOperationFailed();
    }

    /// @dev EIP-196 scalar multiplication. The scalar is range-checked by the caller.
    function _ecMul(uint256[2] memory point, uint256 scalar) private view returns (uint256[2] memory out) {
        uint256[3] memory input = [point[0], point[1], scalar];
        bool ok;
        assembly {
            ok := staticcall(gas(), 0x07, input, 0x60, out, 0x40)
        }
        if (!ok) revert GroupOperationFailed();
    }

    function _isValidVerificationKey(VerificationKey calldata vk) private pure returns (bool) {
        if (vk.ic.length != PUBLIC_INPUT_COUNT + 1) return false;

        if (vk.alpha1[0] >= FIELD_MODULUS || vk.alpha1[1] >= FIELD_MODULUS) return false;
        if (vk.alpha1[0] == 0 && vk.alpha1[1] == 0) return false;

        for (uint256 i = 0; i < 4; ++i) {
            if (vk.beta2[i] >= FIELD_MODULUS) return false;
            if (vk.gamma2[i] >= FIELD_MODULUS) return false;
            if (vk.delta2[i] >= FIELD_MODULUS) return false;
        }
        if (_isZeroG2(vk.beta2) || _isZeroG2(vk.gamma2) || _isZeroG2(vk.delta2)) return false;

        for (uint256 i = 0; i < vk.ic.length; ++i) {
            if (vk.ic[i][0] >= FIELD_MODULUS || vk.ic[i][1] >= FIELD_MODULUS) return false;
            if (vk.ic[i][0] == 0 && vk.ic[i][1] == 0) return false;
        }

        return true;
    }

    function _isZeroG2(uint256[4] calldata point) private pure returns (bool) {
        return point[0] == 0 && point[1] == 0 && point[2] == 0 && point[3] == 0;
    }
}